---
name: Check if all commits are signed
on:
  pull_request_target:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}--${{ github.head_ref }} # github.ref is unavailable in case of pull_request_target
  cancel-in-progress: true
jobs:
  check-commit-signing:
    uses: ./.github/workflows/check.yaml
    permissions:
      contents: read
      pull-requests: write
